apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: presetserver-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: presetserver
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 10
